spring:
  application:
    name: zuul-service

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-a:
      path: /eureka-client/**
      serviceId: eureka-client