app:
  id: SampleApp
# will inject 'application' namespace in bootstrap phase
apollo:
  meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true

spring:
  application:
    name: zuul-service

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#zuul:
#  routes:
#    api-a:
#      path: /eureka-client/**
#      serviceId: eureka-client

management:
  endpoints:
    web:
      exposure:
        include: '*'
